# Ref: https://docs.gitlab.com/ee/ci/yaml/README.html
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
image: gradle:alpine

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

stages:
  - lint
  - test
  - build

cache:
  paths:
    - .gradle

lint_code:
  stage: lint
  script:
    - make lint

test:
  stage: test
  script:
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - build/reports/
    reports:
      junit:
        - build/test-results/test/**/TEST-*.xml
    expire_in: 3 days
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

build:
  stage: build
  script: ./gradlew build -x test
  artifacts:
    paths:
      - build/libs
    expire_in: 1 week
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
