name: Danger CI

on:
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    name: Danger CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        run: yarn add danger

      - name: Danger CI Check
        uses: danger/danger-js@9.1.8
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GH_RELEASE_TOKEN }}